name: Angular CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm install typescript@^5.3
      - run: npm install --force
      - run: npm run build --if-present
      - name: List files
        run: |
          ls
          pwd
          tree .
