name: Angular CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: |
          npm install typescript@^5.3
          npm install
          npm config set registry https://registry.npmjs.org
          npm install -g @angular/cli@17.0.0
          ng build --output-path docs --base-href /tour-of-heros/
          # ng build --configuration production
          ls
          tree -L 3
      # - run: |
      #     npm install typescript@^5.3
      #     npm install --force
      #     npm run build --if-present
